name: Build and Deploy Node/Javascript Documents


on:
  push:
    branches:
      - main
      - SIDE-2043b-documentation

jobs:
  deploy-developer-hub:
    defaults:
      run:
        working-directory: docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm ci
      - run: npm run build:production
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.HELPS_DOCS_DEPLOY_KEY }}
          publish_branch: gh-pages
          publish_dir: ./docs/public
          force_orphan: true
          external_repository: open-olive/olive-helps
  
  deploy-gh-pages-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - run: |
          cd ./ldk/node
          pwd
          ls -a
          npm ci
          npm run build
          npm run doc

      - run: |
          cd ./ldk/javascript
          npm ci
          npm run build
          npm run doc

      - run: |
          cd ./ldk
          mkdir typedoc-tmp
          cp -r ./node/docs typedoc-tmp/node
          cp -r ./javascript/docs typedoc-tmp/javascript

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./ldk/typedoc-tmp
          destination_dir: ldk
          force_orphan: true