name: Build and Deploy Documents


on:
  push:
    branches:
      - main

jobs:
  deploy-developer-hub:
    defaults:
      run:
        working-directory: docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm ci
      - run: npm run build:production
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.HELPS_DOCS_DEPLOY_KEY }}
          publish_branch: gh-pages
          publish_dir: ./docs/public
          force_orphan: true
          external_repository: open-olive/olive-helps
  deploy-node:
    defaults:
      run:
        working-directory: ldk/node
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm ci
      - run: npm run build
      - run: npm run doc
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./ldk/node/docs
          destination_dir: ldk/node
          force_orphan: true