name: Go Lint

defaults:
  run:
    working-directory: ldk/go

on:
  push:
  pull_request:
jobs:
  golangci:
    strategy:
      matrix:
        go-version: [1.15.x]
        os:
          - macos-latest
          - windows-latest
    name: lint
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.32
          args: --timeout=10m
          # Only the LDK is checked; does not appear to check examples.
          working-directory: ldk/go
