name: NuGet Publish

on:
  release:
    types: [ published ]

defaults:
  run:
    working-directory: ldk/csharp

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - run: dotnet build OliveHelpsLDK
      - uses: rohith/publish-nuget@v2
        name: Publish to Nuget
        with:
            PROJECT_FILE_PATH: ldk/csharp/OliveHelpsLDK/OliveHelpsLDK/OliveHelpsLDK.csproj
            TAG_COMMIT: false
            NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
            INCLUDE_SYMBOLS: true