name: Prettier

on:
  push:
  pull_request:

jobs:
  check:
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm set audit false
      - run: npm ci
      - run: npm run prettier:all:check